### ISSUE TITLE
Armor

### ISSUE THREAD

**Issue by HoldYourWaffle** [Techern/Igneous-Extras#23]
Should I add this in?

**Comment by CruzBishop** [comment]
I asked a few people back in the IA days and they all said that armor per se wouldn't be suitable (Tools yeah, since MC already has stone tools)

And if you hit someone covered in stone with a diamond sword (or even iron) in real life, the stone would shatter.

Although, you've got me thinking now...
- Stone helmet: Extends your breath meter by ~4 seconds but masks out vision for the outer 10-20% of the screen (like how pumpkins do) - Also requires one glass pane to craft for across the eyes
- Stone boots: You sink in liquids, like how Metal Mario does in Super Mario 64. Can't swim but can walk across the ocean
- Stone gloves: If you punch a Ghast's Fireball, it bounces off
- Full stone outfit: All of the above, but you get a 50% reduction to speed on land and 3x (relative) speed underwater. Also, if you get hit more than three times in five seconds, it shatters
- Full stone outfit plus a secret item (perhaps a nether star) in the left hand (yay, 1.9!), you can walk through lava as well

Hmmmmmmm. Yeah, this could be something fun for 0.9 :+1:

**Comment by HoldYourWaffle** [comment]
Not sure how to implements stone gloves...
But all the other things are nice ideas!

Just wondering, what does the '0.9' version mean, as I see it at multiple issues

**Comment by CruzBishop** [comment]
...Aww, that's right, we don't get gloves :(

Basically, 0.0.1 and 0.0.2 are alpha/development versions and 0.9 will be the beta version (which should have enough features to warrant a MCF topic again), then it's straight to 1.0 which will be the first gold release :)

**Comment by HoldYourWaffle** [comment]
Maybe stone shield instead of gloves?

**Comment by CruzBishop** [comment]
:+1: Any stone shield can push a mob back with minimal damage, but only polished shields can deflect a fireball? (Or would that be bad?)

**Comment by HoldYourWaffle** [comment]
I think that would be cool
(are andesite, diorite, granite also stone in that sentence?)

**Comment by CruzBishop** [comment]
(Yep, they sure are :+1:)

**Comment by HoldYourWaffle** [comment]
I wonder why I never actually got to this...
